# javascript node circleci 2.0 configuration file
#
# check https://circleci.com/docs/2.0/language-javascript/ for more details
#
general:
  branches:
    only:
      - source
    ignore:
      - master
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            sudo npm install hexo-cli -g
            npm install hexo --save
            npm install hexo-deployer-git --save
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Setup Gtihub
          command: |
            git config --global -l
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
      - run:
          name: Generate and publish the blog
          command: |
            hexo clean
            hexo g
            hexo d
